
#include <stdio.h> 
#include <stdlib.h> 
#include <unistd.h> 
#include <errno.h> 
#include <sys/types.h> 
#include <pwd.h>
#include <string.h>
#include <dirent.h>
#include <fcntl.h> 
#include <signal.h>
#include <termios.h>
#include <time.h>
#include <wait.h>
#include <grp.h>
#include <sys/stat.h>
#include <sys/utsname.h>
#include <errno.h>
#include "getHostName.h"
#include "getUserName.h"
#include "getPWD.h"
#include "changeDirectory.h"
#include "getFileInfo.h"
#include "ls.h"
#include "pinfo.h"
#include "history.h"
#include "pathInterconvert.h"